// Languages.tsx
const translations = {
  vi: {
    settings: "Cài đặt",
    security: "Tài khoản và bảo mật",
    sync: "Đồng bộ tin nhắn",
    data: "Quản lý dữ liệu",
    interface: "Giao diện",
    notifications: "Thông báo",
    messages: "Tin nhắn",
    calls: "Cài đặt cuộc gọi",
    utilities: "Tiện ích",
    contacts_description: "Danh sách bạn bè được hiển thị trong danh bạ",
    general: "Cài đặt chung",
    privacy: "Quyền riêng tư",
    contacts: "Danh bạ",
    language: "Ngôn ngữ",
    change_language: "Thay đổi ngôn ngữ",
    show_all_friends: "Hiển thị tất cả bạn bè",
    show_active_friends: "Chỉ hiển thị bạn bè đang sử dụng Zalo",
    vietnamese: "Tiếng Việt",
    english: "English",
    change_password: "Đổi mật khẩu",
    change_password_desc: "Thay đổi mật khẩu đăng nhập của bạn",
    lock_screen: "Khóa màn hình Zalo",
    lock_screen_desc: "Khóa màn hình khi không sử dụng",
    two_factor: "Bảo mật 2 lớp",
    two_factor_desc:
      "Sau khi bật, bạn sẽ được yêu cầu nhập mã OTP hoặc xác thực từ thiết bị di động sau khi đăng nhập",
    // MainContent
    welcome: "Chào mừng đến với",
    welcome_desc:
      "Khám phá những tiện ích hỗ trợ làm việc và trò chuyện cùng người thân, bạn bè được tối ưu hoá cho máy tính của bạn.",
    dark_mode_title: "Giao diện Dark Mode",
    dark_mode_desc: "Thư giãn và bảo vệ mắt với chế độ tối mới trên Sophy PC",
    try_now: "Thử ngay",
    zbiz_title: "Kinh doanh hiệu quả với zBusiness Pro",
    zbiz_desc:
      "Bán hàng chuyên nghiệp với Nhãn Business và Bộ công cụ kinh doanh",
    learn_more: "Tìm hiểu thêm",
    quick_msg_title: "Nhắn tin nhiều hơn, soạn thảo ít hơn",
    quick_msg_desc: "Lưu sẵn các tin nhắn thường dùng để gửi nhanh",
    seamless_title: "Trải nghiệm xuyên suốt",
    seamless_desc: "Kết nối và làm việc trên mọi thiết bị với dữ liệu đồng bộ",
    file_transfer_title: "Gửi File nặng?",
    file_transfer_desc: "Đã có Sophy PC 'xử' hết",
    // SettingsMenu
    account_info: "Thông tin tài khoản",
    file_management: "Quản lý file",
    support: "Hỗ trợ",
    version_info: "Thông tin phiên bản",
    contact: "Liên hệ",
    send_log: "Gửi file log tới Sophy",
    logout: "Đăng xuất",
    logout_confirm_title: "Xác nhận đăng xuất",
    logout_confirm_content: "Bạn có chắc chắn muốn đăng xuất không?",
    agree: "Đồng ý",
    cancel: "Hủy",
    logout_success_title: "Đăng xuất thành công",
    logout_success_content: "Bạn đã đăng xuất thành công!",
    logout_error_title: "Đăng xuất thất bại",
    logout_error_content: "Đăng xuất thất bại, vui lòng thử lại.",
    // SettingsPopover
    upgrade_account: "Nâng cấp tài khoản",
    your_profile: "Hồ sơ của bạn",
    // ChangePasswordModal
    password_mismatch: "Mật khẩu mới và xác nhận mật khẩu không khớp",
    change_password_success: "Đổi mật khẩu thành công",
    change_password_error: "Đổi mật khẩu thất bại. Vui lòng thử lại",
    current_password: "Mật khẩu hiện tại",
    new_password: "Mật khẩu mới",
    confirm_new_password: "Xác nhận mật khẩu mới",
    enter_current_password: "Vui lòng nhập mật khẩu hiện tại",
    enter_new_password: "Vui lòng nhập mật khẩu mới",
    confirm_new_password_required: "Vui lòng xác nhận mật khẩu mới",
    password_min_length: "Mật khẩu phải có ít nhất 6 ký tự",
    confirm: "Xác nhận",
    // EditUserModal
    update_profile: "Cập nhật thông tin cá nhân",
    display_name: "Tên hiển thị",
    enter_display_name: "Nhập tên hiển thị",
    gender: "Giới tính",
    male: "Nam",
    female: "Nữ",
    birthday: "Ngày sinh",
    update: "Cập nhật",
    no_user_id: "Không tìm thấy userId trong localStorage",
    update_success: "Cập nhật thông tin thành công!",
    update_error: "Cập nhật thất bại!",
    // UpdateAvatarModal
    update_avatar: "Cập nhật ảnh đại diện",
    upload_from_computer: "Tải lên từ máy tính",
    select_image_error: "Vui lòng chọn ảnh mới trước khi cập nhật!",
    update_avatar_success: "Cập nhật ảnh đại diện thành công!",
    update_avatar_error: "Cập nhật ảnh đại diện thất bại!",
    // UserModal
    personal_info: "Thông tin cá nhân",
    phone: "Điện thoại",
    undefined: "Không xác định",
    phone_privacy:
      "Chỉ bạn bè có lưu số của bạn trong danh bạ mới xem được số này",
    // NotificationModal
    turn_off_notifications: "Tắt thông báo",
    close: "Đóng",
    notification_1h: "Trong 1 giờ",
    notification_4h: "Trong 4 giờ",
    notification_8am: "Cho đến 8:00 AM",
    notification_indefinite: "Cho đến khi được mở lại",
    // LabelModal
    label: "Phân loại",
    by_label: "Theo thẻ phân loại",
    manage_labels: "Quản lý thẻ phân loại",
    label_customer: "Khách hàng",
    label_family: "Gia đình",
    label_work: "Công việc",
    label_friends: "Bạn bè",
    label_later: "Trả lời sau",
    // AutoDeleteModal
    auto_delete_messages: "Tin nhắn tự xóa",
    auto_delete_1d: "1 ngày",
    auto_delete_7d: "7 ngày",
    auto_delete_14d: "14 ngày",
    auto_delete_never: "Không bao giờ",
    // ChatHeader
    loading: "Đang tải...",
    edit: "Chỉnh sửa",
    community: "Cộng đồng",
    members: "thành viên",
    add_to_community: "Thêm bạn vào cộng đồng",
    video_call: "Cuộc gọi video",
    search_messages: "Tìm kiếm tin nhắn",
    conversation_info: "Thông tin hội thoại",
    // ChatList
    private_chat: "Trò chuyện riêng",
    more: "Thêm",
    pin_conversation: "Ghim hội thoại",
    mark_unread: "Đánh dấu chưa đọc",
    hide_chat: "Ẩn trò chuyện",
    delete_conversation: "Xóa hội thoại",
    report: "Báo xấu",
    no_messages: "Chưa có tin nhắn",
    no_conversations: "Không có hội thoại nào",
    // ChatNav
    all: "Tất cả",
    unread: "Chưa đọc",
    mark_as_read: "Đánh dấu đã đọc",
    // Header
    search: "Tìm kiếm",
    add_friend: "Thêm bạn",
    create_group: "Tạo nhóm chat",

    show_birthdate: "Hiển thị ngày sinh",
    show_birthdate_desc: "Cho phép hiển thị ngày sinh của bạn",
    show_read_receipts: "Hiển thị trạng thái 'Đã xem'",
    show_read_receipts_desc:
      "Cho phép hiển thị trạng thái 'Đã xem' trong tin nhắn",
    allow_strangers_find: "Cho phép người lạ tìm thấy bạn qua số điện thoại",
    allow_strangers_find_desc:
      "Cho phép người lạ tìm thấy và kết bạn qua số điện thoại của bạn",
    block_messages: "Chặn tin nhắn",
    block_messages_desc: "Danh sách chặn tin nhắn của bạn",
    block_list: "Danh sách chặn",
    allow_strangers_connect: "Cho phép người lạ kết bạn",
    allow_strangers_connect_desc:
      "Cho phép người lạ kết bạn qua các phương thức",
    qr_code: "Mã QR của tôi",
    common_groups: "Nhóm chung",
    zalo_card: "Danh thiếp Zalo",
    suggested_friends: "Gợi ý 'Có thể bạn quen'",
    invalid_age: "Tuổi phải từ 13 đến 123!",
    invalid_age_min: "Tuổi phải lớn hơn hoặc bằng 13",
    invalid_age_max: "Tuổi phải nhỏ hơn hoặc bằng 123",
    invalid_date: "Ngày sinh không hợp lệ",
    light: "Sáng",
    dark: "Tối",
    system: "Hệ Thống",
    chat_background: "Hình nền chat",
    use_avatar_as_background: "Sử dụng Avatar làm hình nền",
    same_password_error: "Mật khẩu mới không được trùng với mật khẩu hiện tại",

    friend_list: "Danh sách bạn bè",
    group_community_list: "Danh sách nhóm và cộng đồng",
    friend_requests: "Lời mời kết bạn",
    group_invites: "Lời mời vào nhóm và cộng đồng",
    cancel_request: "Thu hồi lời mời",
    unblock: "Bỏ chặn",
    no_blocked_users: "Không có người dùng nào bị chặn",
  },
  en: {
    settings: "Settings",
    security: "Account & Security",
    sync: "Message Sync",
    data: "Data Management",
    interface: "Interface",
    notifications: "Notifications",
    messages: "Messages",
    calls: "Call Settings",
    utilities: "Utilities",
    contacts_description: "Friends list displayed in contacts",
    general: "General Settings",
    privacy: "Privacy",
    contacts: "Contacts",
    language: "Language",
    change_language: "Change language",
    show_all_friends: "Show all friends",
    show_active_friends: "Only show friends using Zalo",
    vietnamese: "Vietnamese",
    english: "English",
    change_password: "Change Password",
    change_password_desc: "Change your login password",
    lock_screen: "Lock Zalo Screen",
    lock_screen_desc: "Lock the screen when not in use",
    two_factor: "Two-Factor Authentication",
    two_factor_desc:
      "When enabled, you’ll be required to enter an OTP or authenticate from a mobile device after logging in",
    // MainContent
    welcome: "Welcome to",
    welcome_desc:
      "Discover utilities optimized for your computer to support work and chat with family and friends.",
    dark_mode_title: "Dark Mode Interface",
    dark_mode_desc:
      "Relax and protect your eyes with the new dark mode on Sophy PC",
    try_now: "Try Now",
    zbiz_title: "Effective Business with zBusiness Pro",
    zbiz_desc: "Sell professionally with Business Label and Business Tools",
    learn_more: "Learn More",
    quick_msg_title: "Message More, Type Less",
    quick_msg_desc: "Save frequently used messages for quick sending",
    seamless_title: "Seamless Experience",
    seamless_desc: "Connect and work on any device with synchronized data",
    file_transfer_title: "Sending Large Files?",
    file_transfer_desc: "Sophy PC handles it all",
    // SettingsMenu
    account_info: "Account Information",
    file_management: "File Management",
    support: "Support",
    version_info: "Version Information",
    contact: "Contact",
    send_log: "Send Log File to Sophy",
    logout: "Log Out",
    logout_confirm_title: "Confirm Logout",
    logout_confirm_content: "Are you sure you want to log out?",
    agree: "Agree",
    cancel: "Cancel",
    logout_success_title: "Logout Successful",
    logout_success_content: "You have successfully logged out!",
    logout_error_title: "Logout Failed",
    logout_error_content: "Logout failed, please try again.",
    // SettingsPopover
    upgrade_account: "Upgrade Account",
    your_profile: "Your Profile",
    // ChangePasswordModal
    password_mismatch: "New password and confirmation password do not match",
    change_password_success: "Password changed successfully",
    change_password_error: "Failed to change password. Please try again",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_new_password: "Confirm New Password",
    enter_current_password: "Please enter your current password",
    enter_new_password: "Please enter your new password",
    confirm_new_password_required: "Please confirm your new password",
    password_min_length: "Password must be at least 6 characters",
    confirm: "Confirm",
    // EditUserModal
    update_profile: "Update Personal Information",
    display_name: "Display Name",
    enter_display_name: "Enter display name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    birthday: "Birthday",
    update: "Update",
    no_user_id: "User ID not found in localStorage",
    update_success: "Information updated successfully!",
    update_error: "Update failed!",
    // UpdateAvatarModal
    update_avatar: "Update Avatar",
    upload_from_computer: "Upload from Computer",
    select_image_error: "Please select a new image before updating!",
    update_avatar_success: "Avatar updated successfully!",
    update_avatar_error: "Failed to update avatar!",
    // UserModal
    personal_info: "Personal Information",
    phone: "Phone",
    undefined: "Undefined",
    phone_privacy:
      "Only friends who have your number in their contacts can see this number",
    // NotificationModal
    turn_off_notifications: "Turn Off Notifications",
    close: "Close",
    notification_1h: "For 1 hour",
    notification_4h: "For 4 hours",
    notification_8am: "Until 8:00 AM",
    notification_indefinite: "Until turned back on",
    // LabelModal
    label: "Label",
    by_label: "By Label",
    manage_labels: "Manage Labels",
    label_customer: "Customer",
    label_family: "Family",
    label_work: "Work",
    label_friends: "Friends",
    label_later: "Reply Later",
    // AutoDeleteModal
    auto_delete_messages: "Auto-Delete Messages",
    auto_delete_1d: "1 day",
    auto_delete_7d: "7 days",
    auto_delete_14d: "14 days",
    auto_delete_never: "Never",
    // ChatHeader
    loading: "Loading...",
    edit: "Edit",
    community: "Community",
    members: "members",
    add_to_community: "Add to Community",
    video_call: "Video Call",
    search_messages: "Search Messages",
    conversation_info: "Conversation Info",
    // ChatList
    private_chat: "Private Chat",
    more: "More",
    pin_conversation: "Pin Conversation",
    mark_unread: "Mark as Unread",
    hide_chat: "Hide Chat",
    delete_conversation: "Delete Conversation",
    report: "Report",
    no_messages: "No messages yet",
    no_conversations: "No conversations yet",
    // ChatNav
    all: "All",
    unread: "Unread",
    mark_as_read: "Mark as Read",
    // Header
    search: "Search",
    add_friend: "Add Friend",
    create_group: "Create Group Chat",

    show_birthdate: "Show Birthdate",
    show_birthdate_desc: "Allow your birthdate to be displayed",
    show_read_receipts: "Show Read Receipts",
    show_read_receipts_desc: "Allow read receipts to be displayed in messages",
    allow_strangers_find: "Allow Strangers to Find You by Phone Number",
    allow_strangers_find_desc:
      "Allow strangers to find and connect with you via your phone number",
    block_messages: "Block Messages",
    block_messages_desc: "Your message block list",
    block_list: "Block List",
    allow_strangers_connect: "Allow Strangers to Connect",
    allow_strangers_connect_desc:
      "Allow strangers to connect via various methods",
    qr_code: "My QR Code",
    common_groups: "Common Groups",
    zalo_card: "Zalo Card",
    suggested_friends: "Suggested 'You May Know'",
    invalid_age: "Age must be between 13 and 123!",
    invalid_age_min: "Age must be at least 13",
    invalid_age_max: "Age must be at most 123",
    invalid_date: "Invalid birthdate",
    light: "Light",
    dark: "Dark",
    system: "System",
    chat_background: "Chat Background",
    use_avatar_as_background: "Use Avatar as Chat Background",
    same_password_error: "New password cannot be the same as current password",
    friend_list: "Friends List",
    group_community_list: "Groups and Communities List",
    friend_requests: "Friend Requests",
    group_invites: "Group and Community Invites",
    cancel_request: "Cancel Request", // 
    unblock: "Unblock",
    no_blocked_users: "No users have been blocked",
  },
};

export default translations;
